  name: bump

  on:
    push:
      paths:
        - 'package.json'
      branches: [ main ]
    workflow_dispatch:
  
  jobs:
    publish-client:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 16
            registry-url: 'https://registry.npmjs.org'
        - run: yarn
        - run: yarn build
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


